version: 2
project_name: smv

env:
  - CGO_ENABLED=0

builds:
  - main: ./main.go
    binary: smv
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    flags:
      - -trimpath
        
checksum:
  name_template: "smv_checksum.txt"
